# Generated by Django 3.2.9 on 2021-11-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211103_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
    ]
