# Generated by Django 3.2.9 on 2021-11-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_note_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
